### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by wutong8023** [THU-KEG/MetaKGR#1]
Traceback (most recent call last):
  File "/home/astone/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/astone/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/astone/experiment/MetaKGR/src/experiments.py", line 811, in <module>
    run_experiment(args)
  File "/home/astone/experiment/MetaKGR/src/experiments.py", line 792, in run_experiment
    train(lf)
  File "/home/astone/experiment/MetaKGR/src/experiments.py", line 255, in train
    lf.run_train(train_data, dev_data)
  File "/home/astone/experiment/MetaKGR/src/learn_framework.py", line 145, in run_train
    loss = self.loss(mini_batch)
  File "/home/astone/experiment/MetaKGR/src/emb/emb.py", line 103, in loss
    pred_scores = mdl.forward(e1, r, kg)
  File "/home/astone/experiment/MetaKGR/src/emb/fact_network.py", line 145, in forward
    stacked_inputs = self.bn0(stacked_inputs)
  File "/home/astone/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/astone/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/home/astone/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Hi, would you please help me solve this problem? It appears when I try to run this command: 
./experiment-emb.sh ./configs/fb15k-237-conve.sh --train 1

**Comment by davidlvxin** [comment]
It's a cuDNN error. Please make sure your computer has at least one GPU and pytorch with CUDA is installed successfully.
